name: Development Feature
description: Define a new feature for Octopus Copilot
body:
  - type: markdown
    attributes:
      value: |
        # Octopus Copilot: Development Feature
        This issue defines a new feature to be added to Octopus Copilot.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the feature?
      placeholder: Feature description
    validations:
      required: true

  - type: textarea
    id: prompt
    attributes:
      label: Chat query
      description: What prompt would you like to see added?
      placeholder: Chat prompt
    validations:
      required: true

  - type: textarea
    id: action
    attributes:
      label: Action
      description: What should this prompt do?
      placeholder: Prompt action
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example
      description: Are there existing examples of this prompt?
      placeholder: Existing examples
    validations:
      required: false

