#!/usr/bin/env python3

# Octoterra has a script that generates a JSONL file for fine-tuning an AI based on the Terraform configurations
# included in the integration tests.
# These training examples are then merged with the project examples generated by the generate_finetune_data.py script.
# The merged file is used to fine-tune the AI model.
#
# The process to generate the training examples is as follows:
# 1. delete any existing *.jsonl files in this directory
# 2. Run the generate_finetune_data.py script from theOctopusTerraformExport/finetune directory
# 3. Run the generate_finetune_data.py script from this directory
# 4. Run the merge_training_files.py script from this directory
# 5. The merged file is octopus_ai_prompt_merged.jsonl, which can be used to train the AI model.

with open("octopus_ai_prompt_response_projects.jsonl", "r") as f:
    project_examples = f.read()

with open(
    "/home/matthew/Code/OctopusTerraformExport/finetune/octopus_ai_prompt_response.jsonl",
    "r",
) as f:
    general_examples = f.read()

with open("octopus_ai_prompt_merged.jsonl", "w") as f:
    # Write the project examples first
    f.write(project_examples)
    # Then write the general examples
    f.write(general_examples)
